# Generated by Django 3.2.6 on 2021-08-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixels_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('image', models.URLField()),
                ('genre', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(default='null', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fav_console',
            field=models.CharField(default='null', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.URLField(default='http://www.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='null', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fav_games',
            field=models.ManyToManyField(to='pixels_api.Games'),
        ),
    ]
