# Generated by Django 3.2.6 on 2021-08-20 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixels_api', '0002_auto_20210820_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fav_games',
        ),
        migrations.AddField(
            model_name='user',
            name='fav_games',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='pixels_api.games'),
            preserve_default=False,
        ),
    ]
