# Generated by Django 3.2.6 on 2021-08-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixels_api', '0002_alter_useraccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='age',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='fav_console',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='fav_games',
            field=models.ManyToManyField(to='pixels_api.Games'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
