# Generated by Django 3.2.6 on 2021-08-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixels_api', '0003_auto_20210821_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='age',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='fav_console',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='fav_games',
            field=models.ManyToManyField(blank=True, to='pixels_api.Games'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
