# Generated by Django 3.2.6 on 2021-08-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixels_api', '0003_auto_20210820_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fav_games',
        ),
        migrations.AddField(
            model_name='user',
            name='fav_games',
            field=models.ManyToManyField(to='pixels_api.Games'),
        ),
    ]
