# Generated by Django 3.2.6 on 2021-08-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixels_api', '0005_useraccount_users_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='users_liked',
        ),
    ]
